# 定义工作流的名称
name: teach-study Release

# 定义一个 push 事件：当推送带有 "v*" 的标签时触发
on:
  push:
    tags:
      - "v*"

# 定义时区
env:
  TZ: Asia/Shanghai

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4        
          
          - name: Download artifact
            uses: actions/download-artifact@v3
            with:
              name: go_webdav_client-build
    
          - name: Create GitHub Release
            uses: softprops/action-gh-release@v1
            with:
              tag_name: ${{ github.ref_name }} # 使用触发的标签名称
              name: auto release ${{ github.ref_name }}
              files: go_webdav_client* # 将下载的二进制文件发布到 release 中
              draft: false
              prerelease: false
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 的 token 来授权发布